name: 'TODO Comments'
on: ['push']
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@master'
      - uses: 'alstr/todo-to-issue-action@v4.10.2'
        id: 'todo'
